### PR TITLE
Pass tofu char to consult--location-candidate (#37)

### PR DESCRIPTION
**Pull request by northgaard**

### CODE REVIEW

**Comment by gagbo** [comment]
Hello,

Thanks for the report and the fix, but I don't think that passing the char directly is the fix here, I'll take care of it when I have time (I think you want to pass `marker` again, but I won't test for a while)

**Comment by northgaard** [comment]
I just checked and it seems you are right. consult--line-candidates simply repeats the line number, so I've updated the PR to do the same. Works fine in my testing, but feel free to fix it however you see fit.

**Comment by northgaard** [comment]
Ha, that's a great point! Updated.

**Comment by gagbo** [comment]
Thanks for your patience!

**Pull request merged**
